## 开启Swagger的Basic认证功能
swagger:
  basic:
   enable: true
   username: zengf
   password: Zf$123456
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /easyboot
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB  #最大文件大小
      max-request-size: 10MB #最大请求大小
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false  #是否启用模板缓存
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
    cache-names:  easyboot
    redis:
      time-to-live: 200s
      cache-null-values: false
#安全域名配置
base:
    corsList:
      - http://localhost
      - http://localhost:9528
#mybatis配置信息
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
      # 数据库相关配置
      db-config:
        #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
        id-type: auto
        #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
        field-strategy: not_empty
        #驼峰下划线转换
        table-underline: true
        #是否开启大写命名，默认不开启
        #capital-mode: true
        #逻辑删除配置
        #logic-delete-value: 1
        #logic-not-delete-value: 0
        db-type: mysql
      #刷新mapper 调试神器
      refresh: true
      banner: false
    # 原生配置
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
#jwt配置
jwt:
  config:
    key: zfcoding
    expiration: 86400
    remember: 604800
    jwtRedisKey: 'zfsecurity:simpleboot:jwt:'
    header: ZFSimple-Token
zfcustom:
  config:
    ignoreConfig:
      # 需要过滤的请求，不限方法
      options:
        - "/**"
      pattern:
        - "/**/*.html"
        - "/**/*.css"
        - "/**/*.js"
        - "/doc.html"
        - "/swagger-resources"
        - "/swagger-ui.html"
        - "/swagger-resources/**"
        - "/v2/api-docs"
        - "/v2/api-docs-ext"
        - "/webjars/**"
        - "/auth/login"
        - "/auth/authCode"
        - "/druid/**"
        - "/hello/**"
        - "/test/**"


